name: Push actions

on:
  push:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - uses: "actions/checkout@v2"

        - name: HACS validation
          uses: "hacs/integration/action@master"
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CATEGORY: "integration"

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"

  style:
    runs-on: ubuntu-latest
    name: Check style formatting
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Set up Python 3.8
      with:
        python-version: 3.8
    - name: set PY
      run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v1.0.0

  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v1.6.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          package-name: release-please-action
